name: Build with Gradle.

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          distribution: 'corretto'
          java-version: 17

      - name: Build with Gradle.
        run: ./gradlew build --no-daemon --scan

      - name: Upload spotbugs report artifact.
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs report
          path: build/reports/spotbugs.html
